{
  "branches": ["main", "beta"],
  "plugins":
    [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/github",
      [
        "@codedependant/semantic-release-docker",
        {
          "dockerRegistry": "ghcr.io",
          "dockerProject": "betagouv",
          "dockerImage": "matomo-to-pg/sync",
          "dockerTags":
            [
              "{{#if prerelease.[0]}}{{prerelease.[0]}}{{else}}latest{{/if}}",
              "{{major}}-{{#if prerelease.[0]}}{{prerelease.[0]}}{{else}}latest{{/if}}",
              "{{major}}.{{minor}}-{{#if prerelease.[0]}}{{prerelease.[0]}}{{else}}latest{{/if}}",
              "{{version}}",
            ],
          "dockerArgs":
            {
              "BUILD_VERSION": "{{major}}.{{minor}}.{{patch}}",
              "COMMIT_SHA": "{{git_sha}}",
            },
        },
      ],
    ],
}
